import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  standardsSidebar: [
    'definitions',
    {
      type: 'category',
      label: 'Standards',
      link: {
        type: 'doc',
        id: 'standards/index',
      },
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'standards/hcs-1',
          label: 'HCS-1: File Management',
        },
        {
          type: 'doc',
          id: 'standards/hcs-2',
          label: 'HCS-2: Topic Registries',
        },
        {
          type: 'doc',
          id: 'standards/hcs-3',
          label: 'HCS-3: Recursion',
        },
        {
          type: 'doc',
          id: 'standards/hcs-5',
          label: 'HCS-5: Hashinals',
        },
        {
          type: 'doc',
          id: 'standards/hcs-6',
          label: 'HCS-6: Dynamic Hashinals',
        },
        {
          type: 'doc',
          id: 'standards/hcs-7',
          label: 'HCS-7: Smart Hashinals',
        },
        {
          type: 'category',
          label: 'HCS-8: Poll Topic',
          link: {
            type: 'doc',
            id: 'standards/hcs-8/index',
          },
          collapsible: true,
          collapsed: true,
          items: [
            'standards/hcs-8/examples',
            'standards/hcs-8/operations',
            'standards/hcs-8/references',
            'standards/hcs-8/rejected-ideas',
            'standards/hcs-8/specification',
          ],
        },
        {
          type: 'category',
          label: 'HCS-9: Poll Metadata',
          link: {
            type: 'doc',
            id: 'standards/hcs-9/index',
          },
          collapsible: true,
          collapsed: true,
          items: [
            'standards/hcs-9/active-discussions',
            'standards/hcs-9/extending-the-modules',
            'standards/hcs-9/formatting-guide',
            'standards/hcs-9/glossary',
            {
              type: 'category',
              label: 'Implementation',
              collapsible: true,
              collapsed: true,
              items: [{type: 'autogenerated', dirName: 'standards/hcs-9/implementation'}],
            },
            'standards/hcs-9/references',
            'standards/hcs-9/schema-definitions',
            {
              type: 'category',
              label: 'Specification',
              collapsible: true,
              collapsed: true,
              items: [{type: 'autogenerated', dirName: 'standards/hcs-9/specification'}],
            },
          ],
        },
        {
          type: 'doc',
          id: 'standards/hcs-10/index',
          label: 'HCS-10: OpenConvAI',
        },
        {
          type: 'doc',
          id: 'standards/hcs-11',
          label: 'HCS-11: Profile Metadata',
        },
        {
          type: 'doc',
          id: 'standards/hcs-13',
          label: 'HCS-13: Schema Registry',
        },
        {
          type: 'category',
          label: 'HCS-20: Auditable Points',
          collapsible: true,
          collapsed: true,
          items: [{type: 'autogenerated', dirName: 'standards/hcs-20'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Libraries',
      link: {
        type: 'doc',
        id: 'libraries/index',
      },
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Recursion SDK',
          link: {
            type: 'doc',
            id: 'libraries/recursion-sdk/index',
          },
          collapsible: true,
          collapsed: true,
          items: [
            'libraries/recursion-sdk/what-is-recursion',
            'libraries/recursion-sdk/usage', 
            'libraries/recursion-sdk/functions',
            'libraries/recursion-sdk/advanced-examples'
          ],
        },
        {
          type: 'category',
          label: 'Hashinal Wallet Connect',
          link: {
            type: 'doc',
            id: 'libraries/hashinal-wc/index',
          },
          collapsible: true,
          collapsed: true,
          items: [
            'libraries/hashinal-wc/installation',
            'libraries/hashinal-wc/methods',
            'libraries/hashinal-wc/topics',
            'libraries/hashinal-wc/usage-with-nextjs',
            'libraries/hashinal-wc/usage-with-react',
            'libraries/hashinal-wc/usage-with-recursion',
            'libraries/hashinal-wc/usage-with-vite'
          ],
        },
        {
          type: 'category',
          label: 'Standards SDK',
          link: {
            type: 'doc',
            id: 'libraries/standards-sdk/index',
          },
          collapsible: true,
          collapsed: true,
          items: [
            'libraries/standards-sdk/overview',
            'libraries/standards-sdk/hcs-2',
            {
              type: 'category',
              label: 'HCS-10',
              link: {
                type: 'doc',
                id: 'libraries/standards-sdk/hcs-10/index',
              },
              collapsible: true,
              collapsed: true,
              items: [
                'libraries/standards-sdk/hcs-10/base-client',
                'libraries/standards-sdk/hcs-10/browser',
                'libraries/standards-sdk/hcs-10/connections-manager',
                'libraries/standards-sdk/hcs-10/examples',
                'libraries/standards-sdk/hcs-10/server',
                'libraries/standards-sdk/hcs-10/index'
              ],
            },
            'libraries/standards-sdk/hcs-3',
            'libraries/standards-sdk/hcs-7',
            'libraries/standards-sdk/hcs-11',
            'libraries/standards-sdk/hcs-20',
            'libraries/standards-sdk/inscribe',
            'libraries/standards-sdk/utils-services'
          ],
        },
        {
          type: 'category',
          label: 'Standards Agent Kit',
          link: {
            type: 'doc',
            id: 'libraries/standards-agent-kit/index',
          },
          collapsible: true,
          collapsed: true,
          items: [
            'libraries/standards-agent-kit/overview',
            'libraries/standards-agent-kit/core-client',
            'libraries/standards-agent-kit/examples',
            'libraries/standards-agent-kit/langchain-tools',
            'libraries/standards-agent-kit/plugins'
          ],
        },
      ],
    },
    'tooling',
  ],
};

export default sidebars;
