case-studies:
  label: Case Studies
  permalink: /case-studies
  description: Case Studies for applications built using Hashgraph Online.

defi:
  label: DeFi
  permalink: /defi
  description: Decentralized Finance (DeFi) related content

hedera:
  label: Hedera
  permalink: /hedera
  description: Topics related to the Hedera network and ecosystem

hcs-20:
  label: HCS-20
  permalink: /hcs-20
  description: Information about the HCS-20 token standard

bonzo-finance:
  label: Bonzo Finance
  permalink: /bonzo-finance
  description: Content related to Bonzo Finance project

dao:
  label: DAO
  permalink: /dao
  description: Topics related to Decentralized Autonomous Organizations

hcs:
  label: HCS
  permalink: /hcs
  description: Information about Hedera Consensus Service

web3:
  label: Web3
  permalink: /web3
  description: Content related to Web3 technologies and applications

blockchain:
  label: Blockchain
  permalink: /blockchain
  description: Topics covering blockchain technology and its applications

sdk:
  label: SDK
  permalink: /sdk
  description: Software Development Kits and developer tools

open-source:
  label: Open Source
  permalink: /open-source
  description: Open source projects, libraries and contributions

ai:
  label: AI
  permalink: /ai
  description: Artificial Intelligence related content

standards:
  label: Standards
  permalink: /standards
  description: Standards and specifications

agents:
  label: Agents
  permalink: /agents
  description: Content related to AI agents and agentic systems

hcs-10:
  label: HCS-10
  permalink: /hcs-10
  description: Information about the HCS-10 protocol

hcs-11:
  label: HCS-11
  permalink: /hcs-11
  description: Information about the HCS-11 protocol

openconvai:
  label: OpenConvAI
  permalink: /openconvai
  description: Content related to OpenConvAI

hackathon:
  label: Hackathon
  permalink: /hackathon
  description: Hackathon events and competitions

winners:
  label: Winners
  permalink: /winners
  description: Winners and achievements

agent-kit:
  label: Agent Kit
  permalink: /agent-kit
  description: Hedera Agent Kit related content

eliza-os:
  label: Eliza OS
  permalink: /eliza-os
  description: Eliza OS framework and applications

case-study:
  label: Case Study
  permalink: /case-study
  description: Individual case study posts

points:
  label: Points
  permalink: /points
  description: Points and rewards systems

langchain:
  label: LangChain
  permalink: /langchain
  description: LangChain integration and tools

community:
  label: Community
  permalink: /community
  description: Community-related content and events

updates:
  label: Updates
  permalink: /updates
  description: Platform updates and release announcements

hol-desktop:
  label: HOL Desktop
  permalink: /hol-desktop
  description: HOL Desktop application releases and features

hcs-14:
  label: HCS-14
  permalink: /hcs-14
  description: HCS-14 Universal Agent ID standard updates

agent-id:
  label: Agent ID
  permalink: /agent-id
  description: Topics related to universal agent identifiers

registry-broker:
  label: Registry Broker
  permalink: /registry-broker
  description: Registry Broker platform news and tutorials

tashi:
  label: Tashi
  permalink: /tashi
  description: Tashi ecosystem announcements and progress

hcs-15:
  label: HCS-15
  permalink: /hcs-15
  description: HCS-15 Petals profile standard updates

hcs-16:
  label: HCS-16
  permalink: /hcs-16
  description: HCS-16 Floras AppNet standard updates

hcs-17:
  label: HCS-17
  permalink: /hcs-17
  description: HCS-17 State Hash standard updates

monthly-recap:
  label: Monthly Recap
  permalink: /monthly-recap
  description: Monthly recap posts highlighting recent developments

neuron:
  label: Neuron
  permalink: /neuron
  description: Content related to Neuron and machine commerce

ai-agents:
  label: AI Agents
  permalink: /ai-agents
  description: AI agent development and applications

identity:
  label: Identity
  permalink: /identity
  description: Digital identity, identifiers, and DIDs

privacy:
  label: Privacy
  permalink: /privacy
  description: Privacy topics for agents and applications

compliance:
  label: Compliance
  permalink: /compliance
  description: Regulatory compliance and related tooling

hcs-proposal:
  label: HCS Proposal
  permalink: /hcs-proposal
  description: Proposals and drafts for new HCS standards

trustmesh:
  label: TrustMesh
  permalink: /trustmesh
  description: TrustMesh product updates and case studies

scend:
  label: Scend
  permalink: /scend
  description: Content related to Scend and its integrations

civic-tech:
  label: Civic Tech
  permalink: /civic-tech
  description: Civic technology and governance use cases

hashnet-mcp:
  label: Hashnet MCP
  permalink: /hashnet-mcp
  description: Hashnet MCP Server updates and guides

mcp:
  label: MCP
  permalink: /mcp
  description: Model Context Protocol (MCP) content and integrations

erc-8004:
  label: ERC-8004
  permalink: /erc-8004
  description: ERC-8004 trustless agents and registry interoperability

x402:
  label: x402
  permalink: /x402
  description: Coinbase x402 payments and credit flows

hcs-21:
  label: HCS-21
  permalink: /hcs-21
  description: HCS-21 Adapter Registry standard updates

patchwork:
  label: Patchwork
  permalink: /patchwork
  description: Patchwork AI Standards working sessions and program updates

standards-sdk:
  label: Standards SDK
  permalink: /standards-sdk
  description: Standards SDK releases, demos, and developer tooling

reputation:
  label: Reputation
  permalink: /reputation
  description: Reputation, attestations, and trust signaling topics

hcs-19:
  label: HCS-19
  permalink: /hcs-19
  description: HCS-19 AI Agent Privacy Compliance standard

privacycheq:
  label: PrivacyCheq
  permalink: /privacycheq
  description: PrivacyCheq and aiCheq integrations

machine-commerce:
  label: Machine Commerce
  permalink: /machine-commerce
  description: Machine-to-machine commerce and transactions

partnership:
  label: Partnership
  permalink: /partnership
  description: Partnership announcements and collaborations

moonscape:
  label: Moonscape
  permalink: /moonscape
  description: Moonscape platform and features

mit:
  label: MIT
  permalink: /mit
  description: MIT Media Lab and research collaborations

hcs-1:
  label: HCS-1
  permalink: /hcs-1
  description: Information about the HCS-1 protocol

inscribe-utilities:
  label: Inscribe-Utilities
  permalink: /inscribe-utilities
  description: Incribe Utilities-related content

hgrimoire:
  label: hgrimoire
  permalink: /hgrimoire
  description: Hgrimoire-related content

mesh-network:
  label: Mesh Network
  permalink: /mesh-network
  description: Mesh network technologies and applications

robotics:
  label: Robotics
  permalink: /robotics
  description: Robotics and autonomous systems content

security:
  label: Security
  permalink: /security
  description: Content related to security best practices and encryption

architecture:
  label: Architecture
  permalink: /architecture
  description: System architecture and design patterns

advanced:
  label: Advanced
  permalink: /advanced
  description: Advanced topics and deep technical guides

automation:
  label: Automation
  permalink: /automation
  description: Automation workflows and autonomous agents

websockets:
  label: WebSockets
  permalink: /websockets
  description: Real-time communication and WebSocket patterns

typescript:
  label: TypeScript
  permalink: /typescript
  description: TypeScript specific guides and patterns

virtuals:
  label: Virtuals Protocol
  permalink: /virtuals
  description: Content related to the Virtuals Protocol and ACP

base:
  label: Base
  permalink: /base
  description: Content related to the Base L2 network
discovery:
  label: Discovery
  permalink: /discovery
  description: Content related to agent discovery and registries

fetch-ai:
  label: Fetch.ai
  permalink: /fetch-ai
  description: Content related to Fetch.ai and AgentVerse ecosystem

encryption:
  label: Encryption
  permalink: /encryption
  description: End-to-end encryption and secure communication patterns

tokenization:
  label: Tokenization
  permalink: /tokenization
  description: AI agent tokenization and fractional ownership models

nanda:
  label: NANDA
  permalink: /nanda
  description: MIT NANDA decentralized agent infrastructure and registry

a2a:
  label: A2A Protocol
  permalink: /a2a
  description: Agent-to-Agent communication protocol content
