import { TutorialItem, TutorialCategory } from './types';

export const carouselTutorials: TutorialItem[] = [
  {
    id: 'setup-environment',
    name: 'Setup Environment',
    title: 'Setup Your Development Environment',
    description: 'Configure your development environment with Node.js, create a Hedera testnet account, and install the Standards SDK.',
    href: '/docs/tutorials/getting-started/setup-environment',
    difficulty: 'beginner',
    duration: '10 min',
    standard: 'Setup',
    category: 'Getting Started',
    tags: ['setup', 'basics', 'environment'],
    codeExample: 'npm install @hashgraphonline/standards-sdk',
    learningOutcomes: [
      'Install Node.js and npm',
      'Create a Hedera testnet account',
      'Configure environment variables',
      'Install Standards SDK'
    ],
  },
  {
    id: 'first-hcs-message',
    name: 'First HCS Message',
    title: 'Submit Your First HCS Message',
    description: 'Learn HCS fundamentals by creating topics, submitting messages, and subscribing to real-time updates.',
    href: '/docs/tutorials/getting-started/submit-your-first-hcs-message',
    difficulty: 'beginner',
    duration: '15 min',
    standard: 'HCS Basics',
    category: 'Getting Started',
    tags: ['messages', 'topics', 'consensus'],
    codeExample: 'await client.submitMessage(topicId, message)',
    prerequisites: ['Environment setup completed'],
    learningOutcomes: [
      'Create HCS topics',
      'Submit messages to topics',
      'Subscribe to topic updates',
      'Handle message ordering'
    ],
  },
  {
    id: 'inscribe-file',
    name: 'File Inscription',
    title: 'Inscribe Your First File',
    description: 'Store any file permanently on Hedera using HCS inscriptions. Learn chunking, verification, and retrieval.',
    href: '/docs/tutorials/inscriptions/inscribe-your-first-file',
    difficulty: 'beginner',
    duration: '20 min',
    standard: 'HCS-1',
    category: 'Inscriptions & Storage',
    tags: ['storage', 'files', 'inscriptions'],
    codeExample: 'inscribe(fileBuffer, metadata)',
    prerequisites: ['HCS basics understanding'],
    learningOutcomes: [
      'Inscribe files on-chain',
      'Handle file chunking',
      'Verify inscriptions',
      'Retrieve stored files'
    ],
  },
  {
    id: 'create-hashinal',
    name: 'Create Hashinal NFT',
    title: 'Create NFT with Inscriptions',
    description: 'Build fully on-chain NFTs (Hashinals) where both image and metadata are stored permanently on Hedera.',
    href: '/docs/tutorials/inscriptions/create-nft-with-inscriptions',
    difficulty: 'intermediate',
    duration: '30 min',
    standard: 'HCS-5',
    category: 'Inscriptions & Storage',
    tags: ['nft', 'hashinals', 'tokenization'],
    codeExample: 'createHashinal(fileId, tokenConfig)',
    prerequisites: ['HCS-1 understanding', 'Token service knowledge'],
    learningOutcomes: [
      'Create Hashinal NFTs',
      'Store NFT metadata on-chain',
      'Link inscriptions to tokens',
      'Implement evolving NFTs'
    ],
  },
];

export const tutorialCategories: TutorialCategory[] = [
  {
    title: 'Getting Started',
    description: 'Set up your development environment and learn HCS fundamentals',
    icon: '',
    tutorials: [
      {
        title: 'Setup Your Environment',
        description: 'Configure your development environment with Node.js, create a Hedera testnet account, and install the Standards SDK.',
        href: '/docs/tutorials/getting-started/setup-environment',
        difficulty: 'beginner',
        duration: '10 min',
        standard: 'Setup',
        featured: true,
        tags: ['setup', 'basics'],
      },
      {
        title: 'Submit Your First HCS Message',
        description: 'Learn HCS fundamentals by creating topics, submitting messages, and subscribing to real-time updates.',
        href: '/docs/tutorials/getting-started/submit-your-first-hcs-message',
        difficulty: 'beginner',
        duration: '15 min',
        standard: 'HCS Basics',
        featured: true,
        tags: ['messages', 'topics'],
      },
    ],
  },
  {
    title: 'Inscriptions & Storage',
    description: 'Store data permanently on Hedera using HCS inscriptions',
    icon: '',
    tutorials: [
      {
        title: 'Inscribe Your First File',
        description: 'Store any file permanently on Hedera using HCS inscriptions. Learn chunking, verification, and retrieval.',
        href: '/docs/tutorials/inscriptions/inscribe-your-first-file',
        difficulty: 'beginner',
        duration: '20 min',
        standard: 'HCS-1',
        featured: true,
        tags: ['storage', 'files'],
      },
      {
        title: 'Create NFT with Inscriptions',
        description: 'Build fully on-chain NFTs (Hashinals) where both image and metadata are stored permanently on Hedera.',
        href: '/docs/tutorials/inscriptions/create-nft-with-inscriptions',
        difficulty: 'intermediate',
        duration: '30 min',
        standard: 'HCS-5',
        tags: ['nft', 'hashinals'],
      },
    ],
  },
  {
    title: 'Registries & Discovery',
    description: 'Build decentralized registries for data organization',
    icon: '',
    tutorials: [
      {
        title: 'Create Your First Registry',
        description: 'Build a decentralized registry using HCS-2 for organizing and discovering on-chain data.',
        href: '#',
        difficulty: 'intermediate',
        duration: '25 min',
        standard: 'HCS-2',
        tags: ['registry', 'discovery'],
      },
      {
        title: 'Build a Name Service',
        description: 'Create a decentralized naming system similar to ENS using HCS registries.',
        href: '#',
        difficulty: 'advanced',
        duration: '45 min',
        standard: 'HCS-2',
        tags: ['naming', 'dns'],
      },
    ],
  },
  {
    title: 'AI Agents',
    description: 'Deploy autonomous agents on the Hedera network',
    icon: '',
    tutorials: [
      {
        title: 'Deploy Your First Agent',
        description: 'Create an autonomous AI agent that can communicate through HCS using the OpenConvAI standard.',
        href: '#',
        difficulty: 'intermediate',
        duration: '30 min',
        standard: 'HCS-10',
        tags: ['ai', 'agents'],
      },
      {
        title: 'Agent-to-Agent Messaging',
        description: 'Enable secure, verifiable communication between AI agents on the Hedera network.',
        href: '#',
        difficulty: 'advanced',
        duration: '40 min',
        standard: 'HCS-10',
        tags: ['ai', 'messaging'],
      },
    ],
  },
  {
    title: 'Points & Rewards',
    description: 'Implement auditable points and reward systems',
    icon: '',
    tutorials: [
      {
        title: 'Deploy Points System',
        description: 'Create an auditable points system using HCS-20 for transparent reward distribution.',
        href: '#',
        difficulty: 'intermediate',
        duration: '25 min',
        standard: 'HCS-20',
        tags: ['points', 'rewards'],
      },
      {
        title: 'Build Rewards Program',
        description: 'Implement a complete loyalty program with point minting, transfers, and redemption.',
        href: '#',
        difficulty: 'advanced',
        duration: '50 min',
        standard: 'HCS-20',
        tags: ['loyalty', 'gamification'],
      },
    ],
  },
];